# Generated by Django 6.0.7 on 2026-07-31 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('tmdb_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('rated', models.CharField(blank=True, max_length=20, null=True)),
                ('runtime_min', models.IntegerField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
                ('director', models.TextField(blank=True, null=True)),
                ('writer', models.TextField(blank=True, null=True)),
                ('actors', models.TextField(blank=True, null=True)),
                ('plot', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('awards', models.TextField(blank=True, null=True)),
                ('tagline', models.TextField(blank=True, null=True)),
                ('poster_url', models.URLField(blank=True, max_length=500, null=True)),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('imdb_votes', models.CharField(blank=True, max_length=50, null=True)),
                ('rt_score', models.IntegerField(blank=True, null=True)),
                ('metacritic_score', models.IntegerField(blank=True, null=True)),
                ('tmdb_rating', models.FloatField(blank=True, null=True)),
                ('tmdb_votes', models.IntegerField(blank=True, null=True)),
                ('box_office_usd', models.BigIntegerField(blank=True, null=True)),
                ('budget_usd', models.BigIntegerField(blank=True, null=True)),
                ('revenue_usd', models.BigIntegerField(blank=True, null=True)),
                ('mcu_phase', models.CharField(blank=True, max_length=50, null=True)),
                ('universe', models.CharField(blank=True, max_length=100, null=True)),
                ('decade', models.CharField(blank=True, max_length=20, null=True)),
                ('collection_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tmdb_genres', models.CharField(blank=True, max_length=255, null=True)),
                ('tmdb_keywords', models.TextField(blank=True, null=True)),
                ('production', models.CharField(blank=True, max_length=255, null=True)),
                ('production_countries', models.CharField(blank=True, max_length=255, null=True)),
                ('spoken_languages', models.CharField(blank=True, max_length=255, null=True)),
                ('is_animated', models.BooleanField(default=False)),
                ('is_tv_series', models.BooleanField(default=False)),
                ('is_mcu_canon', models.BooleanField(default=False)),
                ('episode_count', models.IntegerField(blank=True, null=True)),
                ('season_count', models.IntegerField(blank=True, null=True)),
                ('network', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=255)),
                ('character', models.CharField(blank=True, max_length=255, null=True)),
                ('cast_order', models.IntegerField(blank=True, null=True)),
                ('actor_tmdb_id', models.IntegerField(blank=True, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('profile_path', models.URLField(blank=True, max_length=500, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_members', to='movies.movie')),
            ],
            options={
                'ordering': ['cast_order'],
            },
        ),
    ]
